# UDP Image Configuration - Halpe26 (26 keypoints)

detection:
  model_path: yolov8s.pt
  confidence_threshold: 0.5

pose_estimation:
  method: rtmpose_halpe26
  
  rtmpose_halpe26:
    pose_model_url: https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/onnx_sdk/rtmpose-l_simcc-body7_pt-body7-halpe26_700e-384x288-734182ce_20230605.zip
    pose_input_size: [288, 384]
    backend: onnxruntime
    device: cuda
    num_keypoints: 26

input:
  path: demo_data/images/sample.jpg

output:
  path: demo_data/outputs/result_halpe26.jpg
